<?php

namespace Tests\Feature\QuoteManagement;

use App\Models\Quote;
use App\Models\User;
use App\Service\QuoteManagementService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ConvertQuoteToOrderTest extends TestCase
{
    private QuoteManagementService $quoteManagement;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->quoteManagement = app(QuoteManagementService::class);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testConvertQuoteToOrder()
    {
        $quote = Quote::factory()
            ->has(Quote\QuoteShipper::factory(), 'quoteShipper')
            ->has(Quote\QuoteVehicle::factory(), 'quoteVehicle')
            ->has(Quote\QuoteDestination::factory(), 'quoteDestination')
            ->has(Quote\QuoteOrigin::factory(), 'quoteOrigin')
            ->has(Quote\QuoteTransport::factory(), 'quoteTransport')
            ->create();

        $order = $this
            ->quoteManagement
            ->convertQuoteToOrder($quote);

        $this->assertEquals(Quote::STATUS_APPROVED, $order->status);
    }
}
